language: ruby
cache: bundler

rvm:
  - 2.4.2
  - 2.2.0
  - 2.1.2
  - 2.1.0
  - 2.0.0
  - 1.9.3
env:
  - ISOLATED=true

script: 'bundle exec rake'

notifications:
  email:
    on_failure: change
    on_success: never